best-shopper-team/grace-shopper

- package-lock.json
- server/db/models/address.js
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/orderItem.js
- server/db/models/user.js
> Add models

- server/db/models/category.js
- server/db/models/product.js
- server/db/models/review.js
> adds category, product, review models

- server/db/db.js
- server/db/models/index.js
- server/db/models/orderItem.js
- server/db/models/review.js
> set up associations, changed db name

- script/seed.js
- server/db/models/order.js
> seed file updated

- script/seed.js
- server/db/models/product.js
> fixed seed file

- server/api/index.js
- server/api/products.js
- server/api/reviews.js
- server/api/users.js
> Added products, users, and reviews API routes

- server/api/index.js
- server/api/orderItems.js
> adds orderItems routes

- server/api/users.js
> fixed user api routes

- server/api/orders.js
> added include to route for orderitems  to single past order

- client/components/allProductDumb.js
- client/components/allProducts.js
- client/components/index.js
- client/components/main.js
- client/routes.js
- client/store/allProducts.js
- client/store/index.js
- public/style.css
> add all products component

- server/api/products.js
> Add categories to products

- client/components/SingleProduct.js
- client/components/index.js
- client/routes.js
- client/store/index.js
- client/store/reviews.js
- client/store/singleProduct.js
- public/style.css
> singleProduct component added, singleProduct & reviews reducers created

- client/components/main.js
- client/routes.js
- public/style.css
> Allproduct fixes

- server/db/models/index.js
- server/db/models/order.js
- server/db/models/session.js
- server/db/models/user.js
> remove session model and validates email on user model

- client/components/SingleProduct.js
- client/components/allProducts.js
- client/components/allProducts.spec.js
- client/components/singleProduct.spec.js
- client/components/user-home.spec.js
- package-lock.json
- package.json
> added single product spec and fixed allproduct spec

- client/components/cart.js
- client/components/checkout.js
- client/store/cart.js
- server/api/orders.js
> Checkout submit page

- client/components/SingleProduct.js
- client/store/cart.js
- server/api/orders.js
> can add items to cart, create cart for user and unauth

- client/components/SingleProduct.js
- client/components/cart.js
- client/components/main.js
- client/store/cart.js
- server/api/orders.js
- server/auth/index.js
> Cart persists

- client/components/allProducts.js
- client/components/searchBar.js
- client/store/categories.js
> all products now render when there is a search term

- client/components/auth-form.js
- client/components/user-home.js
- client/store/user.js
> adds username field to signup

- client/components/main.js
- client/routes.js
- public/style.css
> add products on / and fix cart nav

- client/components/cart.js
- client/components/checkout.js
- client/store/cart.js
- client/store/orders.js
- package-lock.json
- server/api/orders.js
checkout, submit, deletes quantity from products
shoudl work for auth or unauthorized users
> Continue checkout submit

- client/components/allUsers.js
- script/seed.js
- server/api/users.js
-- admin can set a user's passwordReset boolean to FALSE
-- still need to check if user needs password reset on login
-- also fixes a typo in seed file -- run npm seed after merging and pulling this
> Admin trigger password reset

- client/components/allProducts.js
> add create categories for admins

- client/components/cart.js
- client/routes.js
- client/store/cart.js
- server/api/orders.js
> cart bug fixed

- client/components/SingleProduct.js
- client/components/writeReview.js
> make writeReview component slightly less crappy

- client/components/checkout.js
- client/components/main.js
- client/routes.js
> checkout form ui

- client/components/userOrderHistory.js
> fixes bug switching between admin all orders and order history

- client/components/main.js
> fixed div arrangement to get styling back

- client/components/allProducts.js
- public/style.css
> Add category fix

- client/components/searchBar.js
- public/style.css
> addsearch style fix sort of

- server/api/admin.js
- server/db/models/product.js
> fix post route so default url appears

- client/components/cart.js
- client/components/checkout.js
- public/style.css
> Checkout validation cart

- server/api/email.js
- server/api/orders.js
- server/db/models/order.js
> send email when order is shipped

- client/components/allProducts.js
- public/style.css
- server/api/admin.js
> category delete possible

- script/seed.js
> update seed file

- client/components/orderHistory.js
- client/components/userOrderHistory.js
> update order history views

- client/components/checkout.js
- server/api/email.js
> email fixed

- script/seed.js
> remove active carts from seed

- client/components/userOrderHistory.js
- public/style.css
> orderhistory shows subtotal

- client/components/addProduct.js
- client/components/allProducts.js
Can now add a product, give it categories, and it WILL show up on the allProducts page (and be filterable) immediately!
> new prod / category bug fix

- client/components/SingleProduct.js
> add inactive display for non admins
